---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  inspec_tests:
  - path: test/integration/default/inspec

platforms:
  - name: ubuntu-14.04
    driver:
      box: bento/ubuntu-14.04
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
  - name: debian-8
    driver:
      box: bento/debian-8
  - name: debian-9
    driver:
      box: bento/debian-9

suites:
  - name: chef-13
    attributes:
      nginx:
        config:
          mainconfig_include: "/etc/nginx/mainconfig_custom_include.conf"
    run_list:
      - recipe[apt]
      - recipe[nginx_lwrp::official-repo]
      - recipe[nginx_lwrp]
      - recipe[nginx_test::cleaner_check]
      - recipe[nginx_test]
      - recipe[nginx_test::helper_templates]
      - recipe[nginx_test::streams]
