---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_path: ./test/shared/
#  require_chef_omnibus: 11.18.12

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.8

suites:
  - name: default
    attributes:
      nginx:
        mainconfig_include: "/etc/nginx/mainconfig_custom_include.conf"
    run_list:
      - recipe[apt]
      - recipe[nginx]
      - recipe[nginx_test::cleaner_check]
      - recipe[nginx_test]
      - recipe[nginx_test::logrotation]
      - recipe[nginx_test::helper_templates]
  - name: streams
    run_list:
      - recipe[apt]
      - recipe[nginx::official-repo]
      - recipe[nginx]
      - recipe[nginx_test::streams]
