---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero
  chef_license: accept

verifier:
  name: inspec
  inspec_tests:
  - path: test/integration/default/inspec

platforms:
  - name: ubuntu-14.04-docker
    driver_config:
      image: ubuntu-upstart:14.04
      disable_upstart: false
      run_command: '/sbin/init'
      provision_command:
        - apt-get install -y net-tools gnupg # For InSpec & Chef
  - name: ubuntu-16.04-docker
    driver_config:
      image: ubuntu:16.04
      disable_upstart: false
      run_command: '/lib/systemd/systemd'
      provision_command:
        - apt-get install -y net-tools gnupg # For InSpec & Chef
        - systemctl set-default multi-user.target
  - name: ubuntu-18.04-docker
    driver_config:
      image: ubuntu:18.04
      disable_upstart: false
      run_command: '/lib/systemd/systemd'
      provision_command:
        - apt-get install -y net-tools gnupg # For InSpec & Chef
        - systemctl set-default multi-user.target
  - name: debian-8-docker
    driver_config:
      image: debian:8
      disable_upstart: false
      run_command: '/lib/systemd/systemd'
      provision_command:
        - apt-get install -y net-tools gnupg # For InSpec & Chef
        - systemctl set-default multi-user.target
  - name: debian-9-docker
    driver_config:
      image: debian:9
      disable_upstart: false
      run_command: '/lib/systemd/systemd'
      provision_command:
        - apt-get install -y net-tools gnupg # For InSpec & Chef
        - systemctl set-default multi-user.target

suites:
  - name: chef-13
    attributes:
      nginx:
        config:
          mainconfig_include: "/etc/nginx/mainconfig_custom_include.conf"
    run_list:
      - recipe[apt]
      - recipe[nginx_lwrp::official-repo]
      - recipe[nginx_lwrp]
      - recipe[nginx_test::cleaner_check]
      - recipe[nginx_test]
      - recipe[nginx_test::helper_templates]
      - recipe[nginx_test::streams]
    provisioner:
      product_name: chef
      product_version: 13
    includes:
      - ubuntu-16.04-docker
  - name: chef-14
    attributes:
      nginx:
        config:
          mainconfig_include: "/etc/nginx/mainconfig_custom_include.conf"
    provisioner:
      product_name: chef
      product_version: 14
    run_list:
      - recipe[apt]
      - recipe[nginx_lwrp::official-repo]
      - recipe[nginx_lwrp]
      - recipe[nginx_test::cleaner_check]
      - recipe[nginx_test]
      - recipe[nginx_test::helper_templates]
      - recipe[nginx_test::streams]
  - name: chef-15
    attributes:
      nginx:
        config:
          mainconfig_include: "/etc/nginx/mainconfig_custom_include.conf"
    provisioner:
      product_name: chef
      product_version: 15
    run_list:
      - recipe[apt]
      - recipe[nginx_lwrp::official-repo]
      - recipe[nginx_lwrp]
      - recipe[nginx_test::cleaner_check]
      - recipe[nginx_test]
      - recipe[nginx_test::helper_templates]
      - recipe[nginx_test::streams]

