---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_license: accept

verifier:
  name: inspec
  inspec_tests:
  - path: test/integration/default/inspec

platforms:
  - name: ubuntu-14.04
    driver:
      box: bento/ubuntu-14.04
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
  - name: ubuntu-18.04
    driver:
      box: bento/ubuntu-18.04
  - name: debian-8
    driver:
      box: bento/debian-8
  - name: debian-9
    driver:
      box: bento/debian-9

suites:
  - name: chef-13
    attributes:
      nginx:
        config:
          mainconfig_include: "/etc/nginx/mainconfig_custom_include.conf"
    run_list:
      - recipe[apt]
      - recipe[nginx_lwrp::official-repo]
      - recipe[nginx_lwrp]
      - recipe[nginx_test::cleaner_check]
      - recipe[nginx_test]
      - recipe[nginx_test::helper_templates]
      - recipe[nginx_test::streams]
    provisioner:
      product_name: chef
      product_version: 13
    includes:
      - ubuntu-16.04
      - ubuntu-14.04
  - name: chef-14
    attributes:
      nginx:
        config:
          mainconfig_include: "/etc/nginx/mainconfig_custom_include.conf"
    provisioner:
      product_name: chef
      product_version: 14
    run_list:
      - recipe[apt]
      - recipe[nginx_lwrp::official-repo]
      - recipe[nginx_lwrp]
      - recipe[nginx_test::cleaner_check]
      - recipe[nginx_test]
      - recipe[nginx_test::helper_templates]
      - recipe[nginx_test::streams]
  - name: chef-15
    attributes:
      nginx:
        config:
          mainconfig_include: "/etc/nginx/mainconfig_custom_include.conf"
    provisioner:
      product_name: chef
      product_version: 15
    run_list:
      - recipe[apt]
      - recipe[nginx_lwrp::official-repo]
      - recipe[nginx_lwrp]
      - recipe[nginx_test::cleaner_check]
      - recipe[nginx_test]
      - recipe[nginx_test::helper_templates]
      - recipe[nginx_test::streams]

