services:
  - docker

language: ruby
cache: bundler
sudo: false
rvm:
- 2.6.3
bundler_args: "--without kitchen-vagrant"

before_install:
  - gem update --system
  - gem install bundler

script: "bundle exec kitchen test ${INSTANCE} --destroy=always"

env:
  global:
  - KITCHEN_YAML=.kitchen.docker.yml
  matrix:
  - INSTANCE=chef-15-ubuntu-1804-docker
  - INSTANCE=chef-15-ubuntu-1604-docker
  - INSTANCE=chef-15-ubuntu-1404-docker
  - INSTANCE=chef-15-debian-9-docker
  - INSTANCE=chef-15-debian-8-docker
  - INSTANCE=chef-14-ubuntu-1804-docker
  - INSTANCE=chef-14-ubuntu-1604-docker
  - INSTANCE=chef-14-ubuntu-1404-docker
  - INSTANCE=chef-14-debian-9-docker
  - INSTANCE=chef-14-debian-8-docker
  - INSTANCE=chef-13-ubuntu-1604-docker

jobs:
  include:
    - stage: lint
      script:
        - bundle exec rubocop --version
        - bundle exec rubocop .
        - bundle exec foodcritic --version
        - bundle exec foodcritic --contex --epic-fail any .

    - stage: deploy
      if: tag =~ ^v[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}$
      script:
        - openssl aes-256-cbc -K $encrypted_f0160f5b72cb_key -iv $encrypted_f0160f5b72cb_iv -in .travis/dr_agon.pem.enc -out .travis/dr_agon.pem -d
        - bundle exec stove login --username dr_agon --key .travis/dr_agon.pem
        - bundle exec stove --no-git
